var sourcesIndex = {};
sourcesIndex["bindingtester"] = {"name":"","files":["main.rs"]};
sourcesIndex["fdb_bench"] = {"name":"","files":["fdb-bench.rs"]};
sourcesIndex["foundationdb"] = {"name":"","dirs":[{"name":"directory","files":["directory_layer.rs","directory_partition.rs","directory_subspace.rs","error.rs","mod.rs","node.rs"]},{"name":"tuple","files":["element.rs","hca.rs","mod.rs","pack.rs","subspace.rs","versionstamp.rs"]}],"files":["api.rs","database.rs","error.rs","fdb_keys.rs","future.rs","keyselector.rs","lib.rs","mapped_key_values.rs","options.rs","transaction.rs"]};
sourcesIndex["foundationdb_bench"] = {"name":"","files":["lib.rs"]};
sourcesIndex["foundationdb_gen"] = {"name":"","files":["lib.rs"]};
sourcesIndex["foundationdb_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["foundationdb_options_gen"] = {"name":"","files":["foundationdb-options-gen.rs"]};
sourcesIndex["foundationdb_sys"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
