name: Minimal Supported Rust Version

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Find MSRV
        run: nix develop .. -c cargo msrv find -- cargo check --features num-bigint,embedded-fdb-include,fdb-7_4 --no-default-features
        working-directory: ./foundationdb

      - name: Verify MSRV
        run: nix develop .. -c cargo msrv verify -- cargo check --features num-bigint,embedded-fdb-include,fdb-7_4 --no-default-features
        working-directory: ./foundationdb

